### PR TITLE
Feature/23 reset password confirmation

### LINKED ISSUE #23: Reset your password with a code confirmation
# REQUIREMENTS
After that, the user sends us his email, and we check his email. We are going to send him a new code confirmation that he needs to type it and also his new password. The user **needs** to type his new code, if he doesn't do it, he won't be able to change his password  

# DESIGN
image

# Acceptance Criteria
List all required acceptance criteria
- [ ] The layout of the screen requires to be equal to the design image 
- [ ] Create the navigation to arrive at this screen  after touch the "Restablecer clave" button on the *Forgot your password?* screen

### PR DESCRIPTION
**Pull request by OwenRamire**
closes #23 
# Description
- Navigate after the user types his email 
- Pass the user's email by props to display on the new screen at what code we send the new code for confirmation
- Create the layout of the reset pass confirm screen 

  ## Screenshots 

Screenshot_1603927386
Screenshot_1603927391

### CODE REVIEW

**Review by xErikPsx — DISMISSED** [review]
Everything looks good Owen, nice!

**Review by luisarmandodv — APPROVED** [review]

**Review by luisarmandodv — CHANGES_REQUESTED** [review]
I almost forget it, please add PropTypes to the components

**Comment by xErikPsx** [comment]
Good changes Owen!

**Review by xErikPsx — APPROVED** [review]
Those changes seems on point! Nice

**Review by luisarmandodv — APPROVED** [review]

**Pull request merged**
